image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - build
  - test
  - deploy
  - open

#############
# TEMPLATES #
#############
include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: "la-recolte/template"
    file: "/template-test.gitlab-ci.yml"
  - project: "la-recolte/template"
    file: "/template-build.gitlab-ci.yml"
  - project: "la-recolte/template"
    file: "/template-deploy.gitlab-ci.yml"
  - project: "la-recolte/template"
    file: "/template-security.gitlab-ci.yml"
  - project: 'la-recolte/template'
    file: '/template-auto-mr.gitlab-ci.yml'  

#############
# VARIABLES #
#############
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  KUBERNETES_VERSION: 1.12.2
  KUBECONFIG: kube-config.yaml
  DEPLOYMENT_NAME: node-template
  SERVICE_NAME: node-template

###############
# STAGE: BUILD#
###############
build-master:
  extends:
    - .template-build
    - .build-master

build:
  extends:
    - .template-build
    - .build

build-dev:
  extends:
    - .template-build
  script:
    - docker build -f Dockerfile.dev --pull -t "$CI_REGISTRY_IMAGE:ci" .
    - docker push "$CI_REGISTRY_IMAGE:ci"

###############
# STAGE: TEST #
###############
test:
  extends:
    - .template-test
    - .test
  stage: test
  coverage: /All files\s*\|\s*([\d\.]+)/

###############
# STAGE: LINT #
###############
lint:
  extends: .lint
  except:
    - master
  
lint-master:
  extends: .lint
  only:
    - master

###################
# STAGE: SECURITY #
###################
security:
  extends: .template-security

################
# STAGE: DEPLOY#
################
deploy_staging:
  extends: .template-deploy

rollback_staging:
  extends:
    - .template-deploy
    - .rollback

deploy_production:
  extends:
    - .template-deploy
    - .deploy
  variables:
    KUBE_NAMESPACE: production

rollback_production:
  extends:
    - .template-deploy
    - .rollback
  variables:
    KUBE_NAMESPACE: production
  only:
    - master

#################
# STAGE: AUTO-MR#
#################
merge_request:
  extends: .open_merge_request
  only:
    - develop
    
merge_request_production:
  extends: .open_merge_request
  variables:
    SOURCE_BRANCH: staging
    TARGET_BRANCH: master
  only:
    - staging
