version: '3'
services:
  node-template:
    container_name: node-template-service
    build:
      context: .
      dockerfile: dev.Dockerfile
    networks: 
      net:
        aliases:
          - api
    ports:
      - "3000:3000"
    environment:
      - MONGO_TEST_URL=mongodb://database:27017/test-db
      - NODE_ENV=development
    depends_on:
      - database
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./test:/app/test
  database:
    container_name: node-template-db-test
    image: mongo:4.2.5-bionic
    ports:
      - "27017:27017"
    volumes:
    - db-data:/data/db
    networks: 
      net:
        aliases:
          - db
volumes:
  db-data:
networks:
  net:
